services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.9
    container_name: clickhouse
    ports:
      - "8123:8123"    
      - "9000:9000"  
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "123456"